services:
  rag-ui:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./.chroma:/app/.chroma
      - ./data:/app/data
    env_file:
      - .env

  rag-api:
    build: .
    command: uvicorn api.routes:app --host 0.0.0.0 --port 8080
    ports:
      - "8080:8080"
    volumes:
      - ./.chroma:/app/.chroma
      - ./data:/app/data
    env_file:
      - .env

